// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeynHw3fbVt3-AiCe9fXmk4NTCC8mN7Fg',
    appId: '1:263765886437:web:4ec3c69b61d7836e6c5b0c',
    messagingSenderId: '263765886437',
    projectId: 'cv-digital-4525c',
    authDomain: 'cv-digital-4525c.firebaseapp.com',
    storageBucket: 'cv-digital-4525c.firebasestorage.app',
    measurementId: 'G-Z52MJXCNR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDetsQ9YEPSz9b3-ebcL22UgnijKXZ8hJ0',
    appId: '1:263765886437:android:31c5fcf454f0a0746c5b0c',
    messagingSenderId: '263765886437',
    projectId: 'cv-digital-4525c',
    storageBucket: 'cv-digital-4525c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfXcISKsf3w0ZcjwEcBiqpwjN9i43TujI',
    appId: '1:263765886437:ios:ac6e27643fedfbcc6c5b0c',
    messagingSenderId: '263765886437',
    projectId: 'cv-digital-4525c',
    storageBucket: 'cv-digital-4525c.firebasestorage.app',
    iosBundleId: 'com.example.cvdigital.cvDigital',
  );
}
